// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrfPt5Eemma7Qm5aQWR4CoiIJEmvyBjQo',
    appId: '1:890903654390:web:bc9756d03a99cc40f821d7',
    messagingSenderId: '890903654390',
    projectId: 'foodbuddy-bce8a',
    authDomain: 'foodbuddy-bce8a.firebaseapp.com',
    storageBucket: 'foodbuddy-bce8a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzX1gzMA7mh_vooBhJoPpH8R2gYEPZmCc',
    appId: '1:890903654390:android:b4231f2a84635856f821d7',
    messagingSenderId: '890903654390',
    projectId: 'foodbuddy-bce8a',
    storageBucket: 'foodbuddy-bce8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnP1r52378rkK8aU7LYvOgiriqmEP9CJI',
    appId: '1:890903654390:ios:fbcc560ee10bcee0f821d7',
    messagingSenderId: '890903654390',
    projectId: 'foodbuddy-bce8a',
    storageBucket: 'foodbuddy-bce8a.appspot.com',
    iosBundleId: 'com.example.foodbuddy',
  );
}
