// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZyT-POXu6BIUE75gCB4I_eaJEwq169FE',
    appId: '1:731596072175:web:c9d4668f0a24805145271a',
    messagingSenderId: '731596072175',
    projectId: 'foodbuddy-466b4',
    authDomain: 'foodbuddy-466b4.firebaseapp.com',
    storageBucket: 'foodbuddy-466b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEfzx-AMNIe6bkhlWyZSg9SfnUu0QVMC4',
    appId: '1:731596072175:android:8f236e7754e58c7e45271a',
    messagingSenderId: '731596072175',
    projectId: 'foodbuddy-466b4',
    storageBucket: 'foodbuddy-466b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyrFFFu37AIuwVp3jHbfu4rSjqBm96cac',
    appId: '1:731596072175:ios:8cf40c2f3b847ac845271a',
    messagingSenderId: '731596072175',
    projectId: 'foodbuddy-466b4',
    storageBucket: 'foodbuddy-466b4.appspot.com',
    iosBundleId: 'com.example.foodbuddy',
  );

}